#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SKILLS_DIR = path.join(ROOT, 'skills');
const MANIFEST_FILE = path.join(SKILLS_DIR, 'manifest.json');
const README_FILE = path.join(SKILLS_DIR, 'README.md');

function listSkillFiles() {
  return fs.readdirSync(SKILLS_DIR)
    .filter((f) => f.endsWith('.js'))
    .filter((f) => f !== 'index.js')
    .sort();
}

function buildManifest() {
  const skills = [];
  for (const file of listSkillFiles()) {
    const mod = require(path.join(SKILLS_DIR, file));
    skills.push({
      name: mod.name || file.replace(/\.js$/, ''),
      version: mod.version || '1.0.0',
      stage: mod.stage || 'tool',
      description: mod.description || '',
      agents: Array.isArray(mod.agents) ? mod.agents : [],
      file,
      params: mod.params || {},
      contract: mod.contract || null,
    });
  }
  return { generatedAt: new Date().toISOString(), count: skills.length, skills };
}

function writeManifest(manifest) {
  fs.writeFileSync(MANIFEST_FILE, JSON.stringify(manifest, null, 2));
}

function writeReadme(manifest) {
  const tableRows = manifest.skills.map((s) =>
    `| \`${s.name}\` | \`${s.stage}\` | \`${s.file}\` | ${s.agents.length ? s.agents.join(', ') : '—'} | ${s.description || '—'} |`
  ).join('\n');

  const content = `# Skills

Lightweight local skill registry for Hive Mind.
This file is generated by \`npm run skills:sync\` based on \`skills/*.js\`.

## Active Skills

| Skill | Stage | File | Agents | Description |
|------|-------|------|--------|-------------|
${tableRows}

## Structure (Ship-Faster Inspired)

- \`skills/*.js\`: executable skill modules (single source of truth)
- \`skills/index.js\`: auto-load registry
- \`skills/manifest.json\`: generated catalog for UI/tools
- \`scripts/skills-sync.js\`: catalog generator

## Notes

- Keep each skill focused on one job.
- Return \`{ success, result, error? }\` from every \`execute\`.
- Avoid calling other agents from inside skills; orchestrator should coordinate agents.
`;

  fs.writeFileSync(README_FILE, content);
}

function main() {
  const manifest = buildManifest();
  writeManifest(manifest);
  writeReadme(manifest);
  console.log(`Synced ${manifest.count} skill(s) -> skills/manifest.json + skills/README.md`);
}

main();
