/**
 * @fileoverview Mongoose schema for a screenshot comparison result.
 */

const mongoose = require('mongoose');

const ComparisonSchema = new mongoose.Schema(
  {
    /** Reference to the baseline used */
    baseline: { type: mongoose.Schema.Types.ObjectId, ref: 'Baseline', required: true },

    /** URL (relative to storage) of the newly captured screenshot */
    screenshotPath: { type: String, required: true },

    /** URL (relative to storage) of the diff image generated by Resemble.js */
    diffPath: { type: String, required: true },

    /** Percentage of mismatched pixels (0‑100) */
    mismatchPercentage: { type: Number, required: true },

    /** Whether the mismatch exceeds the configured threshold */
    isRegression: { type: Boolean, required: true },

    /** When the comparison was performed */
    comparedAt: { type: Date, default: Date.now },

    /** Optional list of email addresses that should be notified */
    alertRecipients: [{ type: String }]
  },
  { collection: 'comparisons' }
);

module.exports = mongoose.model('Comparison', ComparisonSchema);
